//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fractal.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDS_FRACTAL_CURSOR_POS          102
#define IDD_ADDTEXT                     103
#define IDR_MAINFRAME                   104
#define IDR_FractalTYPE                 105
#define ID_WINDOW_MANAGER               106
#define IDS_WINDOWS_MANAGER             107
#define IDR_FRACTAL                     108
#define IDD_NEW_FRACTAL                 109
#define IDD_DIALOG1                     110
#define IDD_EMBED                       111
#define IDC_CURSOR_MS                   112
#define IDC_CURSOR1                     113
#define IDD_ZOOM_TO_COORDS              114
#define IDC_CURSOR2                     115
#define IDR_CSM_VIEW                    116
#define IDC_CURSOR3                     117
#define IDD_NEW_FRACTAL_TYPE            118
#define IDC_CURSOR4                     119
#define IDR_CSM_JULIA                   120
#define IDD_ANIMATE                     121
#define IDD_EDIT_COLORS                 122
#define IDB_COLORS                      123
#define IDB_PICTURE                     124
#define IDB_BITMAP1                     125
#define IDB_DONATE                      126
#define IDD_HELPDIALOG                  127
#define IDC_CURSOR5                     330
#define IDD_DIALOG2                     331
#define IDD_ADDPICTURE                  331
#define IDB_BITMAP2                     332
#define IDB_TT                          332
#define IDB_TTR                         333
#define IDC_EDIT_WIDTH                  1000
#define IDC_EDIT_HEIGHT                 1001
#define IDC_EDIT_XMIN                   1002
#define IDC_EDIT_XMAX                   1003
#define IDC_EDIT_YMIN                   1004
#define IDC_EDIT_YMAX                   1005
#define IDC_COMBO_RANGE                 1006
#define IDC_EDIT_ITER                   1007
#define IDC_EDIT_P                      1008
#define IDC_FONT                        1009
#define IDC_CHECK_SMOOTH                1010
#define IDC_CHECK_RED                   1011
#define IDC_CHECK_GREEN                 1012
#define IDC_CHECK_BLUE                  1013
#define IDC_EDIT_RR                     1014
#define IDC_EMBEDDED                    1015
#define IDC_EDIT_YMAX2                  1016
#define IDC_EDIT_Q                      1017
#define IDC_RANDOM                      1018
#define IDC_EDIT_RG                     1019
#define IDC_BASE                        1020
#define IDC_EDIT_RB                     1021
#define IDC_RADIO_EXISTING              1022
#define IDC_EDIT_ITER2                  1023
#define IDC_EDIT_STAIRSTEP              1024
#define IDC_OPACITY                     1025
#define IDC_TEXT_OPACITY                1026
#define IDC_RADIO_NEW                   1027
#define IDC_BOLD                        1028
#define IDC_EDIT_ITER3                  1029
#define IDC_EDIT_CALC                   1030
#define IDC_STATIC_COORD                1031
#define IDC_ITALICS                     1032
#define IDC_CHECK_SMOOTH2               1033
#define IDC_CHECK_DROPUNUSED            1034
#define IDC_CHECK_GRADIENT              1035
#define IDC_AUTOPOINT                   1036
#define IDC_ITALICS2                    1037
#define IDC_NOBACKGROUND                1038
#define IDC_GRADIENT1                   1039
#define IDC_POINTSIZE                   1040
#define IDC_GRADIENT2                   1041
#define IDC_CHECK_BASE                  1042
#define IDC_BACKCOLOR                   1043
#define IDC_GRADIENT_COLORS             1044
#define IDC_SORT_LESS                   1045
#define IDC_SORT_GREATER                1046
#define IDC_RANDOM_REVERSE              1047
#define IDC_REVERSE                     1048
#define IDC_CHOOSE_IMAGE                1049
#define IDC_CHECK_USEIMAGE              1050
#define IDC_STEPCOLOR                   1051
#define ID_FRACTAL_STATUS_BAR           1052
#define IDC_CHECK_BLENDBASE             1053
#define IDC_CHECK_BLENDBASE2            1054
#define IDC_CHECK_BLENDFRACTAL          1055
#define IDC_CHOOSE_IMAGE2               1056
#define IDC_STATIC_YMAX                 1057
#define IDC_STATIC_YMIN                 1058
#define IDC_STATIC_XMIN                 1059
#define IDC_STATIC_XMAX                 1060
#define IDC_RADIO_MANDELBROT            1061
#define IDC_STATIC_P                    1062
#define IDC_RADIO_JULIA                 1063
#define IDC_STATIC_Q                    1064
#define IDC_STATIC_FRACTAL_TYPE         1065
#define IDC_CHECK_USEIMAGE2             1066
#define IDC_GRADIENT3                   1067
#define IDC_GRADIENT4                   1068
#define IDC_RADIO_MANDELBROTDRAGON      1069
#define IDC_RADIO_BASE_COLOR            1070
#define IDC_RADIO_MANDELBROTPHOENIX     1071
#define IDC_EDIT1                       1071
#define IDC_EDIT_PICTURENAME            1071
#define IDC_RADIO_BASE_AD               1072
#define IDC_CHOOSE_PICTURE              1072
#define IDC_RADIO_BASE_AD_BASE          1073
#define IDC_RADIO_JULIADRAGON           1074
#define IDC_RADIO_ORBIT_COLOR           1075
#define IDC_RADIO_JULIADRAGON2          1076
#define IDC_RADIO_JULIAPHOENIX          1077
#define IDC_RADIO_BASE_AD_FRACTAL       1078
#define IDC_RADIO_MANDELBROTPHOENIX2    1079
#define IDC_EDIT_OPACITY                1080
#define IDC_RADIO_BUDDHABROT            1081
#define IDC_STATIC_OPACITY              1082
#define IDC_STATIC_OPACITY2             1083
#define IDC_EDIT_TEXT                   1084
#define IDC_EDIT_OPACITY2               1085
#define IDC_STATIC_OPACITY3             1086
#define IDC_STATIC_OPACITY4             1087
#define IDC_GRADIENT5                   1088
#define IDC_TEXTCOLOR                   1089
#define IDC_GRADIENT6                   1090
#define IDC_BOLD_NORMAL                 1091
#define IDC_RADIO_PATH_COLOR_BASE       1092
#define IDC_REVERSE2                    1093
#define IDC_RESET                       1094
#define IDC_RADIO2                      1095
#define IDC_BOLD_HEAVY                  1096
#define IDC_RESET2                      1097
#define IDC_EDIT_COLORS                 1098
#define IDC_STATIC_FONT                 1099
#define IDC_RADIO_PATH_FRACTAL          1100
#define IDC_RADIO_PATH_COLOR_FRACTAL    1101
#define IDC_EDIT_MODE                   1102
#define IDC_STATIC_POINTSIZE            1103
#define IDC_EDIT_XSCALE                 1104
#define IDC_CHECK_RECORD                1105
#define IDC_EDIT_YSCALE                 1106
#define IDC_EDIT_FPS                    1107
#define IDC_EDIT_YSCALE2                1108
#define IDC_EDIT_BAILOUT                1109
#define IDC_CHECK1                      1110
#define IDC_CHECK_TRANSPARENT_COLOR     1110
#define IDC_CHECK_FLYINTO               1111
#define IDC_CHECK_FLYFRAMES             1112
#define IDC_DONATE                      1113
#define IDC_EDIT_FLYFRAMES              1114
#define IDC_HELPDIALOG                  1115
#define IDC_STATIC_FLYFRAMES            1116
#define IDC_CHECK_TRAPX                 1117
#define IDC_STATIC_BASECOLOR            1118
#define IDC_CHECK_FLYFRAMES2            1119
#define IDC_CHECK_PIXELS                1120
#define IDC_STATIC_FRACTALCOLOR         1121
#define IDC_STATIC_INFO                 1122
#define IDC_EDIT_GCR                    1123
#define IDC_STATIC_STEP                 1124
#define IDC_LIST_COLORS                 1125
#define IDC_EDIT_GCG                    1126
#define IDC_EDIT_TRAPX                  1127
#define IDC_CHECK_TRAPY                 1128
#define IDC_EDIT_TRAPY                  1129
#define IDC_CHECK_GCR                   1130
#define IDC_CHECK_GCG                   1131
#define IDC_CHECK_GCB                   1132
#define IDC_EDIT_GCR2                   1133
#define IDC_EDIT_GCB                    1133
#define IDC_TRANSPARENT_COLOR           1134
#define IDC_SLIDER1                     1135
#define IDC_BOLDSLIDER                  1135
#define IDC_STATIC_WEIGHT               1136
#define ID_VIEW_ZOOMOUT                 32771
#define ID_CONTEXT_JULIA                32772
#define ID_CONTEXT_JULIA2X              32773
#define ID_COLORBLEED_UP                32774
#define ID_COLORBLEED_DOWN              32775
#define ID_COLORBLEED_SUBTLEUP          32776
#define ID_COLORBLEED_SUBTLEDOWN        32777
#define ID_IMAGEFILTER_SMOOTH           32778
#define ID_EDIT_DRAGRECTANGLE           32779
#define ID_DRAGRECTANGLE_ZOOMBOX        32780
#define ID_DRAGRECTANGLE_TEXTBOX        32781
#define ID_DRAGRECTANGLE_PICTUREBOX     32782
#define ID_COLORBLEED_PALETTEUP         32783
#define ID_COLORBLEED_PALETTEDOWN       32784
#define ID_CONTEXT_PICTURE_EDIT         32786
#define ID_CONTEXT_PICTURE_DELETE       32787
#define ID_CONTEXT_TEXT_EDIT            32788
#define ID_CONTEXT_TEXT_DELETE          32789
#define ID_CONTEXT_ALL_COLOR            32790
#define ID_CONTEXT_EDIT_COLOR           32791
#define ID_CONTEXT_BLEND_COLOR          32792
#define ID_VIEW_SMALLZOOM               32793
#define ID_VIEW_CONTINUOUSSMALLZOOM     32795
#define ID_VIEW_CONTINUOUS_SMALLZOOM    32797
#define ID_FILE_NEW32798                32798
#define ID_FILE_N                       32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
